
name: Test Flast API

on:
  push:
    branches: main
  pull_request:
    branches: main

#Task
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # To clone code to work on
      # - name: Clone Repo
        # run: git clone https://github.com/mama-19/githubaction_flast.git
      - name: Floder list
      # Terminal
        run: ls 